import { ArrowRight, FolderGit2, BriefcaseBusiness, Mail, Phone } from 'lucide-react';
import ProjectGrid from '@/components/ProjectGrid';
import { FadeUp, Stagger, Item } from '@/components/Motion';

const skills=[
 ['Frontend','React.js · Next.js · Angular.js · TypeScript · JavaScript · HTML5 · SCSS · Bootstrap'],
 ['Backend','Node.js · Nest.js · Express.js · REST APIs · Microservices'],
 ['AI / RAG','Generative AI · RAG Pipelines · Agentic AI · LLM Integration · Vector Search'],
 ['Cloud & DevOps','AWS · Docker · GitHub Actions · Terraform · Ansible · Linux'],
 ['Databases','PostgreSQL · Microsoft SQL Server · Query Optimization'],
 ['Tools','Git · GitHub · Jira · Oracle Commerce Cloud · OSF']
];
const experience=[
 ['Sep 2022 — Present','Tech Matrix · Kuala Lumpur','Full Stack Developer','Contributing to Maybank digital banking platforms across QR payments, e-invoicing, POS integrations, mortgage repricing, settlement automation, and production support.'],
 ['Nov 2021 — Aug 2022','Digisprint Solutions · Hyderabad','Software Engineer','Developed B2B/B2C commerce platforms on Oracle Commerce Cloud with CPQ, multi-site architecture, and Braintree integration.'],
 ['May 2021 — Nov 2021','Mastek · Chennai','Software Engineer','Built customized eCommerce storefronts and enterprise POCs using OCC, OSF, React, JavaScript, and Node.js.'],
 ['Aug 2019 — May 2021','SBrain Online Innovations · Hyderabad','Software Engineer','Built product catalogs, SSEs, email templates, widgets, and backend functionality for Oracle Commerce Cloud platforms.']
];
export default function Page(){return <main>
 <nav className="sticky top-0 z-50 border-b border-white/10 bg-bg/80 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4"><a className="font-syne text-lg font-extrabold">sukesh<span className="text-accent">.</span>dev</a><div className="hidden gap-8 text-sm text-zinc-400 md:flex"><a href="#skills">Skills</a><a href="#projects">Projects</a><a href="#rag">RAG</a><a href="#contact">Contact</a></div></div></nav>
 <section className="mx-auto max-w-6xl px-6 py-24 md:py-32"><FadeUp><p className="mb-5 text-xs font-semibold uppercase tracking-[.25em] text-accent2">Full Stack Engineer · AI · DevOps</p><h1 className="max-w-4xl font-syne text-5xl font-bold leading-tight tracking-tight md:text-7xl">Sukesh Varma <span className="gradient-text">Sangaraju</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-zinc-400">Building scalable digital banking platforms and AI-powered applications using React, Node.js, microservices, and cloud-native architecture. Focused on RAG pipelines, DevOps automation, and high-performance systems.</p><div className="mt-8 flex flex-wrap gap-4"><a href="#projects" className="inline-flex items-center gap-2 rounded-xl bg-accent px-5 py-3 text-sm font-medium text-white">View Projects <ArrowRight size={16}/></a><a href="#contact" className="rounded-xl border border-white/10 px-5 py-3 text-sm text-zinc-200 hover:bg-white/5">Get in Touch</a></div></FadeUp><Stagger className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['6+','Years Experience'],['15+','Maybank Initiatives'],['AI/RAG','Current Focus'],['AWS/Docker','DevOps Stack']].map(s=><Item key={s[1]} className="glass rounded-2xl p-5"><div className="font-syne text-3xl font-bold">{s[0]}</div><div className="mt-1 text-sm text-zinc-500">{s[1]}</div></Item>)}</Stagger></section>
 <section className="border-t border-white/10 px-6 py-20"><div className="mx-auto max-w-6xl"><FadeUp><p className="mb-3 text-xs uppercase tracking-[.22em] text-accent">About</p><h2 className="mb-6 font-syne text-3xl font-bold">AI-ready full stack engineer</h2><p className="max-w-3xl text-base leading-8 text-zinc-400">Full Stack Developer with 6+ years of experience in banking and eCommerce platforms. Currently contributing to Maybank digital systems including payments, merchant platforms, e-invoicing, mortgage journeys, settlement automation, and production support. I’m actively building expertise in Generative AI, Retrieval-Augmented Generation, Agentic AI workflows, and AI-powered automation to combine enterprise data with intelligent user experiences.</p></FadeUp></div></section>
 <section id="skills" className="border-t border-white/10 px-6 py-20"><div className="mx-auto max-w-6xl"><FadeUp><p className="mb-3 text-xs uppercase tracking-[.22em] text-accent">Expertise</p><h2 className="mb-10 font-syne text-3xl font-bold">Technical Skills</h2></FadeUp><Stagger className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{skills.map(([cat,items])=><Item key={cat} className="glass card-hover rounded-2xl p-6"><div className="mb-3 text-xs font-semibold uppercase tracking-widest text-accent2">{cat}</div><p className="text-sm leading-7 text-zinc-400">{items}</p></Item>)}</Stagger></div></section>
 <section id="projects" className="border-t border-white/10 px-6 py-20"><div className="mx-auto max-w-6xl"><FadeUp><p className="mb-3 text-xs uppercase tracking-[.22em] text-accent">Highlights</p><h2 className="mb-10 font-syne text-3xl font-bold">Dynamic Project Portfolio</h2></FadeUp><ProjectGrid/></div></section>
 <section id="rag" className="border-t border-white/10 px-6 py-20"><div className="mx-auto max-w-6xl"><FadeUp><p className="mb-3 text-xs uppercase tracking-[.22em] text-accent">Build in 1–2 days</p><h2 className="mb-6 font-syne text-3xl font-bold">Real RAG Project: AI Document Assistant</h2><div className="glass rounded-3xl p-8"><p className="leading-8 text-zinc-400">Build a PDF question-answering app: upload PDF → extract text → chunk documents → create embeddings → store vectors → retrieve relevant chunks → generate grounded answer with sources. Deploy frontend on Vercel and backend/API routes with Next.js or Render.</p><div className="mt-6 grid gap-4 md:grid-cols-4">{['PDF Upload','Embeddings','Vector Search','LLM Answer'].map(x=><div key={x} className="rounded-2xl border border-white/10 bg-white/[.03] p-4 text-sm text-zinc-300">{x}</div>)}</div></div></FadeUp></div></section>
 <section id="experience" className="border-t border-white/10 px-6 py-20"><div className="mx-auto max-w-6xl"><FadeUp><p className="mb-3 text-xs uppercase tracking-[.22em] text-accent">Career</p><h2 className="mb-10 font-syne text-3xl font-bold">Work Experience</h2></FadeUp><div className="space-y-5">{experience.map(([date,company,role,desc])=><FadeUp key={company} className="glass rounded-2xl p-6"><div className="text-xs text-zinc-500">{date}</div><div className="mt-2 text-sm text-accent2">{company}</div><h3 className="mt-1 font-syne text-xl font-bold">{role}</h3><p className="mt-3 text-sm leading-7 text-zinc-400">{desc}</p></FadeUp>)}</div></div></section>
 <section id="contact" className="border-t border-white/10 px-6 py-20"><div className="mx-auto max-w-4xl text-center"><FadeUp><div className="glass rounded-3xl p-10"><h2 className="font-syne text-3xl font-bold">Let’s build something intelligent</h2><p className="mx-auto mt-4 max-w-xl text-zinc-400">Open to Full Stack, DevOps, AI/RAG engineering roles and freelance AI-powered application work.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><a className="rounded-xl border border-white/10 px-4 py-3 text-sm text-zinc-300" href="mailto:sukeshvarmacse@gmail.com"><Mail className="mr-2 inline" size={16}/>Email</a><a className="rounded-xl border border-white/10 px-4 py-3 text-sm text-zinc-300" href="tel:+601112553109"><Phone className="mr-2 inline" size={16}/>Call</a><a className="rounded-xl border border-white/10 px-4 py-3 text-sm text-zinc-300" href="https://www.linkedin.com/in/sukesh-varma-sangaraju-0ab94415a" target="_blank"><BriefcaseBusiness className="mr-2 inline" size={16}/>LinkedIn</a><a className="rounded-xl border border-white/10 px-4 py-3 text-sm text-zinc-300" href="https://github.com/sukeshcse" target="_blank"><FolderGit2 className="mr-2 inline" size={16}/>GitHub</a></div></div></FadeUp></div></section>
 <footer className="border-t border-white/10 px-6 py-8 text-center text-sm text-zinc-600">Sukesh Varma Sangaraju · Full Stack Developer · Kuala Lumpur, Malaysia · © 2026</footer>
 </main>}
